import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import { Header } from '../../components/common/Header';
import { Footer } from '../../components/common/Footer';
import { Button } from '../../components/common/Button';
import { API_BASE_URL } from '../../config/api';
import { ArrowLeft, ArrowRight, CheckCircle2, Lock, Upload as UploadIcon } from 'lucide-react';

type Draft = { firstName:string; lastName:string; dob:string; nationality:string; email:string; phone:string; address:string; city:string; district:string; languages:string; hostType:string; businessName:string; registrationNumber:string; primaryCity:string; yearsExperience:string; expertise:string; experience:string; proposedTitle:string; proposedDescription:string; proposedCategory:string; proposedDuration:string; maxGuests:string; price:string; availability:string; terms:boolean; privacy:boolean; accuracy:boolean };
type FileKey = 'identity'|'photo'|'license'|'certificate';
const empty: Draft = { firstName:'',lastName:'',dob:'',nationality:'',email:'',phone:'',address:'',city:'',district:'',languages:'',hostType:'individual',businessName:'',registrationNumber:'',primaryCity:'',yearsExperience:'',expertise:'',experience:'',proposedTitle:'',proposedDescription:'',proposedCategory:'Cultural',proposedDuration:'',maxGuests:'8',price:'',availability:'',terms:false,privacy:false,accuracy:false };
const steps = ['Personal details','Host profile','Experience','Documents','Review'];
const loadDraft = (): Draft => { try { return {...empty,...JSON.parse(localStorage.getItem('gn-host-application-draft')||'{}')}; } catch { return empty; } };
const validStep = (step:number,d:Draft) => step===0 ? !![d.firstName,d.lastName,d.dob,d.nationality,d.email,d.phone,d.address,d.city,d.district,d.languages].every(x=>x.trim()) && /^\S+@\S+\.\S+$/.test(d.email) : step===1 ? !!d.primaryCity && !!d.yearsExperience && !!d.expertise && (d.hostType==='individual'||!!d.businessName) : step===2 ? d.experience.trim().length>=50 && !!d.proposedTitle && d.proposedDescription.trim().length>=30 && !!d.proposedDuration && !!d.price && !!d.availability : step===3 ? true : d.terms && d.privacy && d.accuracy;

export default function HostApplicationWizard() {
  const navigate=useNavigate(); const [step,setStep]=useState(0); const [draft,setDraft]=useState(loadDraft); const [files,setFiles]=useState<Record<FileKey,File|null>>({identity:null,photo:null,license:null,certificate:null}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [complete,setComplete]=useState<number|null>(null);
  const update=(key:keyof Draft,value:string|boolean)=>{const next={...draft,[key]:value};setDraft(next);localStorage.setItem('gn-host-application-draft',JSON.stringify(next));};
  const choose=(key:FileKey,value:File|null)=>{if(value&&value.size>10*1024*1024)return setError('Each document must be smaller than 10 MB.');if(value&&!['application/pdf','image/jpeg','image/png'].includes(value.type))return setError('Documents must be PDF, JPG, or PNG files.');setFiles(v=>({...v,[key]:value}));setError('');};
  const next=()=>{if(!validStep(step,draft)){setError('Please complete the required fields before continuing.');return;}setError('');setStep(s=>Math.min(4,s+1));};
  const submit=async()=>{if(!validStep(4,draft)){setError('Please accept all declarations.');return;}setBusy(true);setError('');try{const body=new FormData();body.append('first_name',draft.firstName);body.append('last_name',draft.lastName);body.append('date_of_birth',draft.dob);body.append('nationality',draft.nationality);body.append('email',draft.email);body.append('phone',draft.phone);body.append('address',draft.address);body.append('city',draft.city);body.append('district',draft.district);body.append('languages',draft.languages);body.append('host_type',draft.hostType);body.append('business_name',draft.businessName);body.append('registration_number',draft.registrationNumber);body.append('primary_city',draft.primaryCity);body.append('years_experience',draft.yearsExperience);body.append('expertise',draft.expertise);body.append('experience',draft.experience);body.append('proposedTitle',draft.proposedTitle);body.append('proposedDescription',draft.proposedDescription);body.append('proposedCategory',draft.proposedCategory);body.append('proposedDuration',draft.proposedDuration);body.append('maxGuests',draft.maxGuests);body.append('price',draft.price);body.append('availability',draft.availability);body.append('terms',String(draft.terms));body.append('privacy',String(draft.privacy));body.append('accuracy',String(draft.accuracy));Object.entries(files).forEach(([k,v])=>{if(v)body.append(k,v);});const result=await axios.post(`${API_BASE_URL}/host-applications/submit`,body,{timeout:20000});setComplete(result.data.id);localStorage.removeItem('gn-host-application-draft');}catch(e: unknown){const response=(e as {response?:{data?:{detail?:string}}}).response;setError(response?.data?.detail||'We could not submit your application. Please try again.');}finally{setBusy(false);}};
  if(complete!==null)return <Shell><div className="mx-auto max-w-2xl rounded-3xl bg-white p-8 text-center shadow-sm md:p-14"><CheckCircle2 className="mx-auto mb-5 h-16 w-16 text-emerald-600"/><h1 className="text-3xl font-bold text-[#213448]">Application received</h1><p className="mt-4 text-gray-600">Thank you, {draft.firstName}. Your reference is GH-{String(complete).padStart(6,'0')}. We will contact you at {draft.email} after review.</p><Button className="mt-8" onClick={()=>navigate('/')}>Back to home</Button></div></Shell>;
  return <Shell><button onClick={()=>navigate('/become-host')} className="mb-5 inline-flex items-center gap-2 text-sm text-gray-600"><ArrowLeft className="h-4 w-4"/>Back to host information</button><div className="rounded-3xl bg-white p-5 shadow-sm md:p-10"><h1 className="text-3xl font-bold text-[#213448]">Host application</h1><p className="mt-2 text-gray-600">Complete each section. Your progress is saved on this device.</p><div className="my-8 grid grid-cols-5 gap-2">{steps.map((name,i)=><div key={name} className="text-center"><div className={`mx-auto flex h-9 w-9 items-center justify-center rounded-full text-sm font-bold ${i<step?'bg-emerald-600 text-white':i===step?'bg-[#213448] text-white':'bg-gray-100 text-gray-500'}`}>{i<step?'✓':i+1}</div><p className="mt-2 hidden text-xs text-gray-600 sm:block">{name}</p></div>)}</div>{error&&<p role="alert" className="mb-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  {step===0&&<div className="grid gap-5 md:grid-cols-2"><Input label="First name *" value={draft.firstName} onChange={v=>update('firstName',v)}/><Input label="Last name *" value={draft.lastName} onChange={v=>update('lastName',v)}/><Input label="Date of birth *" type="date" value={draft.dob} onChange={v=>update('dob',v)}/><Input label="Nationality *" value={draft.nationality} onChange={v=>update('nationality',v)}/><Input label="Email *" type="email" value={draft.email} onChange={v=>update('email',v)}/><Input label="Phone *" value={draft.phone} onChange={v=>update('phone',v)}/><Textarea label="Address *" value={draft.address} onChange={v=>update('address',v)}/><Input label="City *" value={draft.city} onChange={v=>update('city',v)}/><Input label="District *" value={draft.district} onChange={v=>update('district',v)}/><Input label="Languages *" value={draft.languages} onChange={v=>update('languages',v)} placeholder="Nepali, English"/></div>}
  {step===1&&<div className="grid gap-5 md:grid-cols-2"><label className="font-medium text-sm text-gray-700">Host type *<select className="mt-2 w-full rounded-xl border border-gray-300 p-3" value={draft.hostType} onChange={e=>update('hostType',e.target.value)}><option value="individual">Individual host</option><option value="business">Business</option><option value="agency">Agency / collective</option></select></label><Input label="Primary city *" value={draft.primaryCity} onChange={v=>update('primaryCity',v)}/><Input label="Years of experience *" type="number" value={draft.yearsExperience} onChange={v=>update('yearsExperience',v)}/><Input label="Areas of expertise *" value={draft.expertise} onChange={v=>update('expertise',v)} placeholder="Culture, trekking, food"/>{draft.hostType!=='individual'&&<><Input label="Business name *" value={draft.businessName} onChange={v=>update('businessName',v)}/><Input label="Registration number" value={draft.registrationNumber} onChange={v=>update('registrationNumber',v)}/></>}</div>}
  {step===2&&<div className="space-y-5"><Textarea label="Tell us about your hosting experience *" value={draft.experience} onChange={v=>update('experience',v)} placeholder="Minimum 50 characters"/><div className="grid gap-5 md:grid-cols-2"><Input label="Proposed experience title *" value={draft.proposedTitle} onChange={v=>update('proposedTitle',v)}/><label className="font-medium text-sm text-gray-700">Category *<select className="mt-2 w-full rounded-xl border border-gray-300 p-3" value={draft.proposedCategory} onChange={e=>update('proposedCategory',e.target.value)}><option>Cultural</option><option>Adventure</option><option>Food</option><option>Nature</option><option>Wellness</option></select></label><Input label="Duration *" value={draft.proposedDuration} onChange={v=>update('proposedDuration',v)}/><Input label="Maximum guests" type="number" value={draft.maxGuests} onChange={v=>update('maxGuests',v)}/><Input label="Price per guest (USD) *" type="number" value={draft.price} onChange={v=>update('price',v)}/><Input label="Availability *" value={draft.availability} onChange={v=>update('availability',v)} placeholder="Weekdays and weekends"/></div><Textarea label="Experience description *" value={draft.proposedDescription} onChange={v=>update('proposedDescription',v)} placeholder="Minimum 30 characters"/></div>}
  {step===3&&<div className="space-y-4"><div className="rounded-xl bg-blue-50 p-4 text-sm text-blue-800"><Lock className="mb-2 h-5 w-5"/>Documents are used only for identity and host verification. PDF, JPG, or PNG; maximum 10 MB each.</div><Upload label="Government-issued photo ID" required value={files.identity} onFile={f=>choose('identity',f)}/><Upload label="Passport-size profile photo" value={files.photo} onFile={f=>choose('photo',f)}/><Upload label="Business or tourism license" value={files.license} onFile={f=>choose('license',f)}/><Upload label="Relevant certification" value={files.certificate} onFile={f=>choose('certificate',f)}/></div>}
  {step===4&&<div><h2 className="text-xl font-bold">Review and declarations</h2><div className="mt-5 grid gap-4 text-sm text-gray-700 sm:grid-cols-2">{[['Applicant',`${draft.firstName} ${draft.lastName}`],['Contact',`${draft.email} · ${draft.phone}`],['Host type',draft.hostType],['Primary city',draft.primaryCity],['Proposed experience',draft.proposedTitle],['Price',draft.price]].map(([a,b])=><div className="rounded-xl bg-gray-50 p-4" key={a}><b>{a}</b><p className="mt-1">{b||'—'}</p></div>)}</div><div className="mt-6 space-y-3 text-sm"><label className="flex gap-3"><input type="checkbox" checked={draft.terms} onChange={e=>update('terms',e.target.checked)}/>I accept the host terms and conditions.</label><label className="flex gap-3"><input type="checkbox" checked={draft.privacy} onChange={e=>update('privacy',e.target.checked)}/>I consent to verification and processing of my documents.</label><label className="flex gap-3"><input type="checkbox" checked={draft.accuracy} onChange={e=>update('accuracy',e.target.checked)}/>I confirm that the information provided is accurate.</label></div></div>}
  <div className="mt-8 flex flex-col-reverse justify-between gap-3 border-t border-gray-200 pt-6 sm:flex-row"><Button variant="secondary" onClick={()=>setStep(s=>Math.max(0,s-1))} disabled={step===0}><ArrowLeft className="mr-2 h-4 w-4"/>Back</Button><Button onClick={step===4?submit:next} disabled={busy}>{step===4?(busy?'Submitting…':'Submit application'):<>Continue <ArrowRight className="ml-2 h-4 w-4"/></>}</Button></div></div></Shell>;
}

function Shell({children}:{children:React.ReactNode}) { return <div className="min-h-screen bg-gray-50"><Header/><main className="container mx-auto max-w-5xl px-4 py-10">{children}</main><Footer/></div>; }
function Input({label,value,onChange,type='text',placeholder=''}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string}) { return <label className="font-medium text-sm text-gray-700">{label}<input className="mt-2 w-full rounded-xl border border-gray-300 p-3" type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>; }
function Textarea({label,value,onChange,placeholder=''}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string}) { return <label className="font-medium text-sm text-gray-700">{label}<textarea className="mt-2 min-h-28 w-full rounded-xl border border-gray-300 p-3" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>; }
function Upload({label,required,value,onFile}:{label:string;required?:boolean;value:File|null;onFile:(f:File|null)=>void}) { return <div className="rounded-xl border border-dashed border-gray-300 p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-medium text-sm text-gray-700">{label} {required&&'*'}</p><p className="mt-1 text-xs text-gray-500">{value?value.name:'PDF, JPG, or PNG · max 10 MB'}</p></div><label className="cursor-pointer rounded-lg border border-gray-300 px-3 py-2 text-sm font-semibold"><UploadIcon className="mr-1 inline h-4 w-4"/>Choose file<input className="hidden" type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>onFile(e.target.files?.[0]??null)}/></label></div>{value&&<button className="mt-2 text-xs text-red-600" onClick={()=>onFile(null)}>Remove file</button>}</div>; }
